# .github/workflows/rss.yml

name: "Check RSS Feed"

on:
  schedule:
    - cron: "0 * * * *" # Ogni ora
  workflow_dispatch: # Permette di eseguire manualmente il workflow

jobs:
  check-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install axios @actions/core @actions/github

      - name: Check RSS Feed for new entries
        id: check_rss
        run: |
          node -e "
          const axios = require('axios');
          const core = require('@actions/core');
          const fs = require('fs');
          const path = './.github/workflows/last_rss_entry.txt';
          
          async function checkFeed() {
            const feedUrl = 'http://createfeed.fivefilters.org/extract.php?url=https%3A%2F%2Fipogo.app%2F&item=div.row&item_title=small&max=5&order=document&guid=0&text_contains%5B0%5D=iOS';
            const response = await axios.get(feedUrl);
            const feedContent = response.data;

            // Parse and check for new items
            const newEntry = feedContent.match(/<item>(.*?)<\/item>/);
            if (!newEntry || newEntry.length < 2) {
              core.setOutput('new_item', 'false');
              return;
            }

            const latestItem = newEntry[1];
            if (fs.existsSync(path)) {
              const lastEntry = fs.readFileSync(path, 'utf-8').trim();
              if (lastEntry === latestItem) {
                core.setOutput('new_item', 'false');
                return;
              }
            }

            // Update cache and trigger
            fs.writeFileSync(path, latestItem);
            core.setOutput('new_item', 'true');
          }
          
          checkFeed().catch(error => core.setFailed(error.message));
          "

      - name: Trigger Update JSON Workflow
        if: steps.check_rss.outputs.new_item == 'true'
        uses: actions/github-script@v4
        with:
          script: |
            const github = require('@actions/github');
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            await octokit.rest.actions.createWorkflowDispatch({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              workflow_id: 'update_json.yml',
              ref: github.context.ref,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
