name: Monitor RSS Feed

on:
  schedule:
    - cron: '0 * * * *' # Ogni ora

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: 'http://createfeed.fivefilters.org/extract.php?url=https%3A%2F%2Fipogo.app%2F&item=div.row&item_title=small&max=5&order=document&guid=0&text_contains%5B0%5D=iOS'
          output_file: 'ipogo_feed.xml'
      - name: Check for changes
        run: |
          if [ $(stat -c%s ipogo_feed.xml) -ne $(cat ipogo_feed.xml.prev) ]; then
            echo "Nuovi elementi nel feed!"
            # Esegui l'azione update_json.yml
            ./.github/workflows/update_json.yml
          fi
          # Salva la dimensione attuale per il prossimo controllo
          echo $(stat -c%s ipogo_feed.xml) > ipogo_feed.xml.prev
