name: Update JSON File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies (if needed)
        run: pip install requests beautifulsoup4

      - name: Run Python script and capture output
        id: run_script
        run: |
          output=$(python json_analyze.py)  # Replace with your script name
          echo "script_output=$output" >> $GITHUB_ENV

      - name: Determine if changes were made
        id: check_output
        run: |
          if [[ "${{ env.script_output }}" == *"No Update Detected"* ]]; then
            echo "changes_made=false" >> $GITHUB_ENV
          else
            echo "changes_made=true" >> $GITHUB_ENV
          fi

      - name: Commit changes (if any)
        if: env.changes_made == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          message: "Update JSON with latest app version (if changed)"
          branch: main  # Adjust the branch name if necessary
          push: true  # Set to false if you don't want automatic pushes

      - name: Create a pull request (if automatic push is disabled)
        if: env.changes_made == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update JSON with latest app version"
          body: "Automatically updated JSON file with latest app information."
          branch: update  # Adjust the branch name if necessary
          commit-message: "Update JSON with latest app version (if changed)"
